### ISSUE TITLE
] and } keys recognized as the same in spanish layout keyboard

### ISSUE THREAD

**Issue by pabolojo** [kelebek333/aziokbd-dkms#1]
After installing your driver I finally got my Microdia keyboard to work. But after testing a bit I saw that the } key is recognized as the ] key, and thus everytime I hit the } key I get an ].
With the command "xev -event keyboard" I get keycode 35 for both of them, rather than 35 for ] and 49 for } (I think that is the code for the } key).

**Comment by kelebek333** [comment]
Hi @pabolojo ,

I'm not the developer of this driver. I've prepared this repo just for easy installation.

Same issue reported to real developer of this driver, You can look following link. 

[ Incorrect Keymapping ](https://bitbucket.org/Swoogan/aziokbd/issues/47/incorrect-keymapping)
